version: '3.7'

services:
  s3:
    image: bitnami/minio:latest 
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: backups
    volumes:
      - minio_data:/data

volumes:
  minio_data:
